"""init schema

Revision ID: d18a1a1347d5
Revises: 
Create Date: 2026-08-09 14:44:59.765327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd18a1a1347d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_article_categories_name')
    )
    op.create_index('idx_article_categories_enabled', 'article_categories', ['is_enabled', 'sort_order'], unique=False)
    op.create_table('banners',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('link_type', sa.String(length=16), server_default='NONE', nullable=False, comment='NONE/ARTICLE/ACTIVITY/URL'),
    sa.Column('link_value', sa.String(length=512), nullable=True, comment='文章ID/活动标识/外链URL'),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('start_at', mysql.DATETIME(fsp=3), nullable=True, comment='生效时间(可选)'),
    sa.Column('end_at', mysql.DATETIME(fsp=3), nullable=True, comment='失效时间(可选)'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("link_type IN ('NONE','ARTICLE','ACTIVITY','URL')", name='chk_banners_link'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_banners_enabled', 'banners', ['is_enabled', 'sort_order'], unique=False)
    op.create_table('coaching_templates',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('scene', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coaching_templates_enabled', 'coaching_templates', ['is_enabled', 'sort_order'], unique=False)
    op.create_table('emotion_feedback_lib',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('mood_type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False, comment='资源导向鼓励话术'),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("mood_type IN ('CALM','HAPPY','ANXIOUS','DOWN','IRRITATED','OTHER')", name='chk_feedback_lib_mood'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_lib', 'emotion_feedback_lib', ['mood_type', 'is_enabled', 'sort_order'], unique=False)
    op.create_table('orders',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('coach_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('service_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('amount_in_cents', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('platform_fee_in_cents', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='CREATED', nullable=False, comment='CREATED/PAID/CLOSED/REFUNDED'),
    sa.Column('paid_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("status IN ('CREATED','PAID','CLOSED','REFUNDED')", name='chk_orders_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no', name='uq_orders_no')
    )
    op.create_index('idx_orders_coach', 'orders', ['coach_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_orders_user', 'orders', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('tags',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False, comment='FIELD/AUDIENCE'),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("type IN ('FIELD','AUDIENCE')", name='chk_tags_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'type', name='uq_tags_name_type')
    )
    op.create_index('idx_tags_enabled', 'tags', ['type', 'is_enabled', 'sort_order'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号，唯一'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 哈希'),
    sa.Column('nickname', sa.String(length=32), nullable=False, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='头像'),
    sa.Column('role', sa.String(length=16), server_default='USER', nullable=False, comment='USER/COACH/ADMIN'),
    sa.Column('status', sa.String(length=16), server_default='ENABLED', nullable=False, comment='ENABLED/DISABLED'),
    sa.Column('privacy_agreed', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否同意隐私政策'),
    sa.Column('last_login_at', mysql.DATETIME(fsp=3), nullable=True, comment='最后登录(UTC)'),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True, comment='软删除(UTC)'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("role IN ('USER','COACH','ADMIN')", name='chk_users_role'),
    sa.CheckConstraint("status IN ('ENABLED','DISABLED')", name='chk_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', name='uq_users_phone')
    )
    op.create_index('idx_users_role_status', 'users', ['role', 'status'], unique=False)
    op.create_table('admin_action_logs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False, comment='COACH_AUDIT_APPROVE/USER_DISABLE/...'),
    sa.Column('target_type', sa.String(length=32), nullable=False, comment='USER/COACH/AUDIT/ARTICLE/...'),
    sa.Column('target_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('detail', mysql.JSON(), nullable=True, comment='变更前后快照'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='fk_admin_logs_admin', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_logs_admin', 'admin_action_logs', ['admin_id', 'created_at'], unique=False)
    op.create_index('idx_admin_logs_target', 'admin_action_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=False, comment='富文本'),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('category_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PUBLISHED', nullable=False, comment='PUBLISHED/DRAFT/OFFLINE'),
    sa.Column('view_count', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('published_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("status IN ('PUBLISHED','DRAFT','OFFLINE')", name='chk_articles_status'),
    sa.ForeignKeyConstraint(['category_id'], ['article_categories.id'], name='fk_articles_category', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_articles_category', 'articles', ['category_id', 'is_pinned', 'status'], unique=False)
    op.create_index('idx_articles_published', 'articles', ['status', sa.literal_column('published_at DESC')], unique=False)
    op.create_table('coach_profiles',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('real_name', sa.String(length=32), nullable=False, comment='真实姓名（仅后台可见）'),
    sa.Column('bio', sa.Text(), nullable=True, comment='个人简介'),
    sa.Column('training_exp', sa.Text(), nullable=True, comment='培训经历'),
    sa.Column('service_concept', sa.String(length=255), nullable=True, comment='服务理念'),
    sa.Column('years_of_experience', mysql.SMALLINT(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('credential_urls', mysql.JSON(), nullable=False, comment='资质证书URL数组（私有）'),
    sa.Column('id_card_url', sa.String(length=512), nullable=True, comment='身份证扫描件（私有）'),
    sa.Column('audit_status', sa.String(length=16), server_default='PENDING', nullable=False, comment='PENDING/APPROVED/REJECTED'),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.00'), nullable=False, comment='综合评分(V1.1聚合)'),
    sa.Column('review_count', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False, comment='评价数(V1.1聚合)'),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("audit_status IN ('PENDING','APPROVED','REJECTED')", name='chk_coach_profiles_audit'),
    sa.CheckConstraint('rating BETWEEN 0.00 AND 5.00', name='chk_coach_profiles_rating'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_coach_profiles_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_coach_profiles_user')
    )
    op.create_index('idx_coach_profiles_audit_rating', 'coach_profiles', ['audit_status', sa.literal_column('rating DESC')], unique=False)
    op.create_table('emotion_journals',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('mood_type', sa.String(length=16), nullable=False, comment='CALM/HAPPY/ANXIOUS/DOWN/IRRITATED/OTHER'),
    sa.Column('content', sa.String(length=500), nullable=False, comment='一句话描述'),
    sa.Column('feedback', sa.String(length=500), nullable=True, comment='话术快照'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("mood_type IN ('CALM','HAPPY','ANXIOUS','DOWN','IRRITATED','OTHER')", name='chk_emotion_journals_mood'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_emotion_journals_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emotion_journals_user', 'emotion_journals', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('payments',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('pay_channel', sa.String(length=16), server_default='WECHAT', nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True, comment='渠道交易号'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='PENDING/SUCCESS/FAILED/REFUNDED'),
    sa.Column('raw_notify', mysql.JSON(), nullable=True, comment='渠道回调原文'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('paid_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','SUCCESS','FAILED','REFUNDED')", name='chk_payments_status'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_payments_order', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', name='uq_payments_transaction')
    )
    op.create_index('idx_payments_order', 'payments', ['order_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex'),
    sa.Column('expires_at', mysql.DATETIME(fsp=3), nullable=False, comment='过期时间(UTC)'),
    sa.Column('revoked_at', mysql.DATETIME(fsp=3), nullable=True, comment='吊销时间(UTC)'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_refresh_tokens_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_hash')
    )
    op.create_index('idx_refresh_tokens_expires', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('self_coaching_records',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('template_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('answers', mysql.JSON(), nullable=False, comment='{stepKey: 回答文本}'),
    sa.Column('action_card', mysql.JSON(), nullable=True, comment='成长行动卡'),
    sa.Column('status', sa.String(length=16), server_default='DRAFT', nullable=False, comment='DRAFT/COMPLETED'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','COMPLETED')", name='chk_self_coaching_status'),
    sa.ForeignKeyConstraint(['template_id'], ['coaching_templates.id'], name='fk_self_coaching_template', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_self_coaching_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_self_coaching_user', 'self_coaching_records', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('system_configs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=64), nullable=False),
    sa.Column('config_value', mysql.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_system_configs_admin', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key', name='uq_system_configs_key')
    )
    op.create_table('template_steps',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('template_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('step_key', sa.String(length=32), nullable=False, comment='STATUS/IDEAL/RESOURCES/ACTION'),
    sa.Column('step_name', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False, comment='内置教练式问句'),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['coaching_templates.id'], name='fk_template_steps_template', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'step_key', name='uq_template_steps')
    )
    op.create_index('idx_template_steps_order', 'template_steps', ['template_id', 'sort_order'], unique=False)
    op.create_table('article_favorites',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('article_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='fk_article_favorites_article', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_article_favorites_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id', name='uq_article_favorites')
    )
    op.create_index('idx_article_favorites_article', 'article_favorites', ['article_id'], unique=False)
    op.create_table('client_relations',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('coach_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('last_appointment_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], name='fk_client_relations_coach', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_client_relations_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'user_id', name='uq_client_relations')
    )
    op.create_index('idx_client_relations_user', 'client_relations', ['user_id'], unique=False)
    op.create_table('coach_audits',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('coach_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('submit_version', mysql.INTEGER(unsigned=True), server_default=sa.text('1'), nullable=False, comment='第几次提交'),
    sa.Column('profile_snapshot', mysql.JSON(), nullable=False, comment='提交时资料快照'),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False, comment='PENDING/APPROVED/REJECTED'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='驳回理由/审核备注'),
    sa.Column('reviewed_by', mysql.BIGINT(unsigned=True), nullable=True, comment='审核管理员'),
    sa.Column('reviewed_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('submitted_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','APPROVED','REJECTED')", name='chk_coach_audits_status'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], name='fk_coach_audits_coach', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='fk_coach_audits_admin', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coach_audits_coach', 'coach_audits', ['coach_id', 'status'], unique=False)
    op.create_index('idx_coach_audits_status', 'coach_audits', ['status', 'submitted_at'], unique=False)
    op.create_table('coach_slots',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('coach_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='日期(Asia/Shanghai)'),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='AVAILABLE', nullable=False, comment='AVAILABLE/BOOKED/OFF'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("status IN ('AVAILABLE','BOOKED','OFF')", name='chk_coach_slots_status'),
    sa.CheckConstraint('end_time > start_time', name='chk_coach_slots_time'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], name='fk_coach_slots_coach', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'date', 'start_time', name='uq_coach_slots')
    )
    op.create_index('idx_coach_slots_available', 'coach_slots', ['coach_id', 'date', 'status'], unique=False)
    op.create_table('coach_tags',
    sa.Column('coach_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('tag_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], name='fk_coach_tags_coach', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_coach_tags_tag', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coach_id', 'tag_id')
    )
    op.create_index('idx_coach_tags_tag', 'coach_tags', ['tag_id'], unique=False)
    op.create_table('services',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('coach_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('service_type', sa.String(length=16), nullable=False, comment='SINGLE/PACKAGE'),
    sa.Column('duration_min', mysql.INTEGER(unsigned=True), server_default=sa.text('60'), nullable=False),
    sa.Column('price_in_cents', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False, comment='价格(分)'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("service_type IN ('SINGLE','PACKAGE')", name='chk_services_type'),
    sa.CheckConstraint('price_in_cents > 0', name='chk_services_price'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], name='fk_services_coach', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_services_coach', 'services', ['coach_id', 'is_enabled'], unique=False)
    op.create_table('appointments',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('appointment_no', sa.String(length=32), nullable=False, comment='业务单号'),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('coach_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('service_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('slot_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('need_desc', sa.String(length=500), nullable=False, comment='教练式提问收集的需求'),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False, comment='PENDING/CONFIRMED/COMPLETED/CANCELLED'),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('cancel_by', mysql.BIGINT(unsigned=True), nullable=True, comment='取消人(用户或教练ID)'),
    sa.Column('idempotency_key', sa.String(length=36), nullable=True, comment='幂等键'),
    sa.Column('completed_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','CONFIRMED','COMPLETED','CANCELLED')", name='chk_appointments_status'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], name='fk_appointments_coach', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='fk_appointments_service', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['coach_slots.id'], name='fk_appointments_slot', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_appointments_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_no', name='uq_appointments_no'),
    sa.UniqueConstraint('slot_id', name='uq_appointments_slot'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_appointments_idem')
    )
    op.create_index('idx_appointments_coach', 'appointments', ['coach_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_appointments_user', 'appointments', ['user_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('case_records',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('coach_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('appointment_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('client_nickname', sa.String(length=32), nullable=True, comment='客户称呼(隐私)'),
    sa.Column('key_points', sa.Text(), nullable=True, comment='对话核心要点'),
    sa.Column('user_gains', sa.Text(), nullable=True, comment='用户收获'),
    sa.Column('followup_advice', sa.Text(), nullable=True, comment='后续跟进建议'),
    sa.Column('duration_min', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='fk_case_records_appointment', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], name='fk_case_records_coach', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_case_records_appointment', 'case_records', ['appointment_id'], unique=False)
    op.create_index('idx_case_records_coach', 'case_records', ['coach_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('reviews',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('appointment_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('coach_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('rating', mysql.SMALLINT(unsigned=True), nullable=False, comment='1-5'),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='chk_reviews_rating'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='fk_reviews_appointment', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], name='fk_reviews_coach', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_reviews_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', name='uq_reviews_appointment')
    )
    op.create_index('idx_reviews_coach', 'reviews', ['coach_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviews_coach', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('idx_case_records_coach', table_name='case_records')
    op.drop_index('idx_case_records_appointment', table_name='case_records')
    op.drop_table('case_records')
    op.drop_index('idx_appointments_user', table_name='appointments')
    op.drop_index('idx_appointments_coach', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('idx_services_coach', table_name='services')
    op.drop_table('services')
    op.drop_index('idx_coach_tags_tag', table_name='coach_tags')
    op.drop_table('coach_tags')
    op.drop_index('idx_coach_slots_available', table_name='coach_slots')
    op.drop_table('coach_slots')
    op.drop_index('idx_coach_audits_status', table_name='coach_audits')
    op.drop_index('idx_coach_audits_coach', table_name='coach_audits')
    op.drop_table('coach_audits')
    op.drop_index('idx_client_relations_user', table_name='client_relations')
    op.drop_table('client_relations')
    op.drop_index('idx_article_favorites_article', table_name='article_favorites')
    op.drop_table('article_favorites')
    op.drop_index('idx_template_steps_order', table_name='template_steps')
    op.drop_table('template_steps')
    op.drop_table('system_configs')
    op.drop_index('idx_self_coaching_user', table_name='self_coaching_records')
    op.drop_table('self_coaching_records')
    op.drop_index('idx_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_expires', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_payments_order', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_emotion_journals_user', table_name='emotion_journals')
    op.drop_table('emotion_journals')
    op.drop_index('idx_coach_profiles_audit_rating', table_name='coach_profiles')
    op.drop_table('coach_profiles')
    op.drop_index('idx_articles_published', table_name='articles')
    op.drop_index('idx_articles_category', table_name='articles')
    op.drop_table('articles')
    op.drop_index('idx_admin_logs_target', table_name='admin_action_logs')
    op.drop_index('idx_admin_logs_admin', table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    op.drop_index('idx_users_role_status', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tags_enabled', table_name='tags')
    op.drop_table('tags')
    op.drop_index('idx_orders_user', table_name='orders')
    op.drop_index('idx_orders_coach', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_feedback_lib', table_name='emotion_feedback_lib')
    op.drop_table('emotion_feedback_lib')
    op.drop_index('idx_coaching_templates_enabled', table_name='coaching_templates')
    op.drop_table('coaching_templates')
    op.drop_index('idx_banners_enabled', table_name='banners')
    op.drop_table('banners')
    op.drop_index('idx_article_categories_enabled', table_name='article_categories')
    op.drop_table('article_categories')
    # ### end Alembic commands ###
